### ISSUE TITLE
Missing fingerprints when passing parameters to asset-url helper (sprockets 2.2.2)

### ISSUE THREAD

**Issue by tagliala** [sstephenson/sprockets#487]
First of all I'm sorry to post this stuff here here because I don't know if this is an issue with sprockets and may be a support request or completely my fault.

I [asked on stackoverflow](http://stackoverflow.com/questions/18043276/missing-fingerprints-when-passing-parameters-to-asset-url-helper-rails3) a couple of months ago without getting answers.

Hope you can help me, I'm going to copy and paste:

I'm writing a gem to include some assets in the rails assets pipeline.

I'm trying to make it works on both Rails3 and Rails4 but I'm experiencing a (minor) issue on Rails 3

The following less file (in vendor/assets/stylesheets):

``` css
@font-face {
  font-family: 'FontAwesome';
  src: asset-url('fontawesome-webfont.eot');
  src: asset-url('fontawesome-webfont.eot?#iefix') format('embedded-opentype'),
       asset-url('fontawesome-webfont.svg#fontawesomeregular') format('svg');
}
```

is compiled differently after `RAILS_ENV=production rake assets:precompile`

Rails 3 output:

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url(/assets/fontawesome-webfont-009f6d1f667cc42c25e712ab3429cbc7.eot);
  src: url(/assets/fontawesome-webfont.eot?#iefix) format('embedded-opentype'), url(/assets/fontawesome-webfont.svg#fontawesomeregular) format('svg');
}
```

Rails 4 output:

``` css
@font-face{
  font-family:'FontAwesome';
  src:url(/assets/fontawesome-webfont-0c21817ea1936b34152cd8667063693e.eot);
  src:url(/assets/fontawesome-webfont-0c21817ea1936b34152cd8667063693e.eot?#iefix) format("embedded-opentype"),url(/assets/fontawesome-webfont-57bf98de995c161f5ba6d1593c404b0e.svg#fontawesomeregular) format("svg")
}
```

Why Rails3 skips fingerprints?

Am I missing something?

Is this a sprocket related issue (Rails 3.2.14 uses 2.2.2, Rails 4 uses 2.10)?

TIA
